name: manual
on:
    workflow_dispatch:
        inputs:
          environment:
            description: "choose env"
            required: true
            default: "staging"
            type: choice
            options:
              - staging
              - production 
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: print
            run: echo "heloooo"
